-- ensure that the table with this name is removed before creating a new one.
DROP TABLE IF EXISTS user_table;

-- Create tg_user table
CREATE TABLE user_table
(
    id            int primary key generated by default as identity,
    user_name     varchar(255),
    email         varchar(255) unique,
    password      varchar(255),
    creation_time timestamp,
    user_role     varchar(255)

);

DROP TABLE IF EXISTS quote;
CREATE TABLE quote
(
    id               int primary key generated by default as identity,
    content          varchar(255),
    quote_like       int,
    quote_dislike    int,
    creation_time    timestamp,
    time_of_updating timestamp,
    email            varchar(100)  references user_table (email)
);